class InitialBalances():
    def __init__(self, dataframe, AccountType):
        self.AccruedInterest = dataframe['accruedInterest']

        self.CashBalance = dataframe['cashBalance']
        self.BondValue = dataframe['bondValue']
        self.CashReceipts = dataframe['cashReceipts']
        self.LiquidationValue = dataframe['liquidationValue']
        self.LongOptionMarketValue = dataframe['longOptionMarketValue']
        self.LongStockValue = dataframe['longStockValue']
        self.MoneyMarketFund = dataframe['moneyMarketFund']
        self.MutualFundValue = dataframe['mutualFundValue']
        self.ShortOptionMarketValue = dataframe['shortOptionMarketValue']
        self.ShortStockValue = dataframe['shortStockValue']
        self.IsInCall = dataframe['isInCall']
        self.PendingDeposits = dataframe['pendingDeposits']
        self.AccountValue = dataframe['accountValue']

        if AccountType == 'CASH':
            self.UnsettledCash = dataframe['unsettledCash']
            self.CashDebitCallValue = dataframe['cashDebitCallValue']
            self.accruedInterest = dataframe['accruedInterest']
            self.cashAvailableForTrading = dataframe['cashAvailableForTrading']
            self.cashAvailableForWithdrawal = dataframe['cashAvailableForWithdrawal']

        if AccountType == 'MARGIN':
            self.AvailableFundsNonMarginableTrade = dataframe['availableFundsNonMarginableTrade']
            self.BuyingPower = dataframe['buyingPower']
            self.CashAvailableForTrading = dataframe['cashAvailableForTrading']
            self.DayTradingBuyingPower = dataframe['dayTradingBuyingPower']
            self.DayTradingBuyingPowerCall = dataframe['dayTradingBuyingPowerCall']
            self.DayTradingEquityCall = dataframe['dayTradingEquityCall']
            self.Equity = dataframe['equity']
            self.EquityPercentage = dataframe['equityPercentage']
            self.LongMarginValue = dataframe['longMarginValue']
            self.MaintenanceCall = dataframe['maintenanceCall']
            self.MaintenanceRequirement = dataframe['maintenanceRequirement']
            self.Margin = dataframe['margin']
            self.MarginEquity = dataframe['marginEquity']
            self.RegTCall = dataframe['regTCall']
            self.ShortMarginValue = dataframe['shortMarginValue']
            self.TotalCash = dataframe['totalCash']
            self.MarginBalance = dataframe['marginBalance']
            self.ShortBalance = dataframe['shortBalance']
        